inf <- read.table("household_power_consumption.txt", header=TRUE, sep=';', na.strings='?')
inf$Date <- as.Date(inf$Date, format='%d/%m/%Y')
sub_inf<-inf[inf$Date=="2007-02-01"|inf$Date=="2007-02-02",]
sub_inf<-transform(sub_inf, timestamp=as.POSIXct(paste(Date, Time)), "%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
plot(sub_inf$timestamp, sub_inf$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(sub_inf$timestamp, sub_inf$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(sub_inf$timestamp, sub_inf$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(sub_inf$timestamp, sub_inf$Sub_metering_2,col="red")
lines(sub_inf$timestamp, sub_inf$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), bty="n", cex=.5)
plot(sub_inf$timestamp,sub_inf$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power", yaxt='n')
axis(2, at = seq(0.0, 0.5, by = 0.1), las=2)
dev.copy(png, file="plot4.png", width=480, height=480)
dev.off()