inf <- read.table("household_power_consumption.txt", header=TRUE, sep=';', na.strings='?')
inf$Date <- as.Date(inf$Date, format='%d/%m/%Y')
sub_inf<-inf[inf$Date=="2007-02-01"|inf$Date=="2007-02-02",]
sub_inf<-transform(sub_inf, timestamp=as.POSIXct(paste(Date, Time)), "%d/%m/%Y %H:%M:%S")
plot(sub_inf$timestamp, sub_inf$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(sub_inf$timestamp, sub_inf$Sub_metering_2,col="red")
lines(sub_inf$timestamp, sub_inf$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), lwd=c(1,1))
dev.copy(png, file="plot3.png", width=480, height=480)
dev.off()